### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sambeano7** [grimdesigns-fivem/roleplay-toolbox#4]
**Describe the bug**
The menu isn't opening for me

**To Reproduce**
Tell Us Steps to reproduce the behavior:
1. Im installing it like i should be

**Expected behavior**
It's not opening

**Roleplay Toolbox (please complete the following information):**
 - Resource Version: [e.g. 1.0.0] 

**Additional context**

**Comment by GrimDesignsFiveM** [comment]
@sambeano7 Sorry we have forgot to update the README the open and close menu control is Numpad9

**Comment by sambeano7** [comment]
it's working now
